// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void Up_Animation(lv_obj_t * TargetObject, int delay);
void hour_Animation(lv_obj_t * TargetObject, int delay);
void min_Animation(lv_obj_t * TargetObject, int delay);
void sec_Animation(lv_obj_t * TargetObject, int delay);
void scrolldot_Animation(lv_obj_t * TargetObject, int delay);
void ui_event_Inicio(lv_event_t * e);
lv_obj_t * ui_Inicio;
lv_obj_t * ui_Scrolldots;
lv_obj_t * ui_UN_Cargador;
lv_obj_t * ui_Bienvenido;
lv_obj_t * ui_logo_unal;
void ui_event_Clock(lv_event_t * e);
lv_obj_t * ui_Clock;
lv_obj_t * ui_Clock_Panel;
lv_obj_t * ui_Dot1;
lv_obj_t * ui_Dot2;
lv_obj_t * ui_Dot3;
lv_obj_t * ui_Dot4;
lv_obj_t * ui_Dot5;
lv_obj_t * ui_Dot6;
lv_obj_t * ui_Dot7;
lv_obj_t * ui_Dot8;
lv_obj_t * ui_Clock_Number1;
lv_obj_t * ui_Clock_Number2;
lv_obj_t * ui_Clock_Number3;
lv_obj_t * ui_Clock_Number4;
lv_obj_t * ui_Min;
lv_obj_t * ui_Hour;
lv_obj_t * ui_Sec;
lv_obj_t * ui_Clock_Center;
lv_obj_t * ui_Date;
lv_obj_t * ui_Scrolldots1;
void ui_event_Usuario(lv_event_t * e);
lv_obj_t * ui_Usuario;
lv_obj_t * ui_Scrolldots2;
lv_obj_t * ui_Seleccion_usuario;
lv_obj_t * ui_muestra;
lv_obj_t * ui_Usuario_seleccionado;
void ui_event_Info(lv_event_t * e);
lv_obj_t * ui_Info;
lv_obj_t * ui_Pary_Cloud;
lv_obj_t * ui_Indicadores;
lv_obj_t * ui_Scrolldots4;
void ui_event_Tiempo_carga(lv_event_t * e);
lv_obj_t * ui_Tiempo_carga;
lv_obj_t * ui_Alarm_container;
lv_obj_t * ui_Tiempo;
lv_obj_t * ui_h2;
lv_obj_t * ui_h5;
lv_obj_t * ui_Carga_completa;
lv_obj_t * ui_Scrolldots5;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void Up_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, -30, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 100);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_1, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, true);
    lv_anim_start(&PropertyAnimation_1);

}
void hour_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 2800);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 300);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_1, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, true);
    lv_anim_start(&PropertyAnimation_1);

}
void min_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 2100);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 200);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_1, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, true);
    lv_anim_start(&PropertyAnimation_1);

}
void sec_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 60000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 3600);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 1000);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_1, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, true);
    lv_anim_start(&PropertyAnimation_1);

}
void scrolldot_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 30, -8);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Inicio(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Up_Animation(ui_logo_unal, 300);
        Up_Animation(ui_Bienvenido, 200);
        scrolldot_Animation(ui_Scrolldots, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        _ui_screen_change(ui_Tiempo_carga, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        _ui_screen_change(ui_Clock, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0);
    }
}
void ui_event_Clock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        Up_Animation(ui_Clock_Panel, 100);
        Up_Animation(ui_Date, 200);
        scrolldot_Animation(ui_Scrolldots1, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        _ui_screen_change(ui_Inicio, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        _ui_screen_change(ui_Usuario, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        hour_Animation(ui_Hour, 200);
        min_Animation(ui_Min, 400);
        sec_Animation(ui_Sec, 0);
    }
}
void ui_event_Usuario(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Up_Animation(ui_Usuario_seleccionado, 300);
        Up_Animation(ui_Seleccion_usuario, 400);
        scrolldot_Animation(ui_Scrolldots2, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        _ui_screen_change(ui_Clock, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        _ui_screen_change(ui_Info, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0);
    }
}
void ui_event_Info(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Up_Animation(ui_Pary_Cloud, 200);
        Up_Animation(ui_Indicadores, 400);
        scrolldot_Animation(ui_Scrolldots4, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        _ui_screen_change(ui_Usuario, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        _ui_screen_change(ui_Tiempo_carga, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0);
    }
}
void ui_event_Tiempo_carga(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Up_Animation(ui_Tiempo, 100);
        Up_Animation(ui_h2, 200);
        Up_Animation(ui_h5, 300);
        Up_Animation(ui_Carga_completa, 400);
        scrolldot_Animation(ui_Scrolldots5, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        _ui_screen_change(ui_Info, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        _ui_screen_change(ui_Inicio, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0);
    }
}

///////////////////// SCREENS ////////////////////
void ui_Inicio_screen_init(void)
{
    ui_Inicio = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Inicio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Inicio, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Inicio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Inicio, &ui_img_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Inicio, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scrolldots = ui_Scrolldots_create(ui_Inicio);
    lv_obj_set_x(ui_Scrolldots, 0);
    lv_obj_set_y(ui_Scrolldots, -8);

    lv_obj_set_style_bg_color(ui_comp_get_child(ui_Scrolldots, UI_COMP_SCROLLDOTS_D1), lv_color_hex(0x101C52),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_Scrolldots, UI_COMP_SCROLLDOTS_D1), 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UN_Cargador = lv_label_create(ui_Inicio);
    lv_obj_set_width(ui_UN_Cargador, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UN_Cargador, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UN_Cargador, 0);
    lv_obj_set_y(ui_UN_Cargador, 75);
    lv_obj_set_align(ui_UN_Cargador, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UN_Cargador, "UN Cargador");
    lv_obj_set_style_text_color(ui_UN_Cargador, lv_color_hex(0x9C9CD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UN_Cargador, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UN_Cargador, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bienvenido = ui_Small_Label_create(ui_Inicio);
    lv_obj_set_x(ui_Bienvenido, 0);
    lv_obj_set_y(ui_Bienvenido, 50);
    lv_obj_set_align(ui_Bienvenido, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Bienvenido, "Bienvenido!");
    lv_obj_set_style_text_color(ui_Bienvenido, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Bienvenido, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo_unal = lv_img_create(ui_Inicio);
    lv_img_set_src(ui_logo_unal, &ui_img_logo_png);
    lv_obj_set_width(ui_logo_unal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logo_unal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_logo_unal, 0);
    lv_obj_set_y(ui_logo_unal, -30);
    lv_obj_set_align(ui_logo_unal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo_unal, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo_unal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_logo_unal, 150);

    lv_obj_add_event_cb(ui_Inicio, ui_event_Inicio, LV_EVENT_ALL, NULL);

}
void ui_Clock_screen_init(void)
{
    ui_Clock = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Clock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Clock, &ui_img_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Clock, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Clock_Panel = lv_obj_create(ui_Clock);
    lv_obj_set_width(ui_Clock_Panel, 180);
    lv_obj_set_height(ui_Clock_Panel, 180);
    lv_obj_set_x(ui_Clock_Panel, 0);
    lv_obj_set_y(ui_Clock_Panel, 40);
    lv_obj_set_align(ui_Clock_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Clock_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Clock_Panel, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Clock_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dot1 = ui_Clock_Dot_create(ui_Clock_Panel);
    lv_obj_set_x(ui_Dot1, -40);
    lv_obj_set_y(ui_Dot1, 15);
    lv_obj_set_align(ui_Dot1, LV_ALIGN_TOP_RIGHT);

    ui_Dot2 = ui_Clock_Dot_create(ui_Clock_Panel);
    lv_obj_set_x(ui_Dot2, -10);
    lv_obj_set_y(ui_Dot2, 50);

    ui_Dot3 = ui_Clock_Dot_create(ui_Clock_Panel);
    lv_obj_set_x(ui_Dot3, 40);
    lv_obj_set_y(ui_Dot3, 15);
    lv_obj_set_align(ui_Dot3, LV_ALIGN_TOP_LEFT);

    ui_Dot4 = ui_Clock_Dot_create(ui_Clock_Panel);
    lv_obj_set_x(ui_Dot4, 10);
    lv_obj_set_y(ui_Dot4, 50);
    lv_obj_set_align(ui_Dot4, LV_ALIGN_TOP_LEFT);

    ui_Dot5 = ui_Clock_Dot_create(ui_Clock_Panel);
    lv_obj_set_x(ui_Dot5, 10);
    lv_obj_set_y(ui_Dot5, -50);
    lv_obj_set_align(ui_Dot5, LV_ALIGN_BOTTOM_LEFT);

    ui_Dot6 = ui_Clock_Dot_create(ui_Clock_Panel);
    lv_obj_set_x(ui_Dot6, 40);
    lv_obj_set_y(ui_Dot6, -15);
    lv_obj_set_align(ui_Dot6, LV_ALIGN_BOTTOM_LEFT);

    ui_Dot7 = ui_Clock_Dot_create(ui_Clock_Panel);
    lv_obj_set_x(ui_Dot7, -10);
    lv_obj_set_y(ui_Dot7, -50);
    lv_obj_set_align(ui_Dot7, LV_ALIGN_BOTTOM_RIGHT);

    ui_Dot8 = ui_Clock_Dot_create(ui_Clock_Panel);
    lv_obj_set_x(ui_Dot8, -40);
    lv_obj_set_y(ui_Dot8, -15);
    lv_obj_set_align(ui_Dot8, LV_ALIGN_BOTTOM_RIGHT);

    ui_Clock_Number1 = ui_Small_Label_create(ui_Clock_Panel);
    lv_obj_set_x(ui_Clock_Number1, 0);
    lv_obj_set_y(ui_Clock_Number1, 0);

    ui_Clock_Number2 = ui_Small_Label_create(ui_Clock_Panel);
    lv_obj_set_x(ui_Clock_Number2, 0);
    lv_obj_set_y(ui_Clock_Number2, 0);
    lv_obj_set_align(ui_Clock_Number2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Clock_Number2, "6");

    ui_Clock_Number3 = ui_Small_Label_create(ui_Clock_Panel);
    lv_obj_set_x(ui_Clock_Number3, 0);
    lv_obj_set_y(ui_Clock_Number3, 0);
    lv_obj_set_align(ui_Clock_Number3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Clock_Number3, "9");

    ui_Clock_Number4 = ui_Small_Label_create(ui_Clock_Panel);
    lv_obj_set_x(ui_Clock_Number4, 0);
    lv_obj_set_y(ui_Clock_Number4, 0);
    lv_obj_set_align(ui_Clock_Number4, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Clock_Number4, "3");

    ui_Min = lv_img_create(ui_Clock_Panel);
    lv_img_set_src(ui_Min, &ui_img_clock_min_png);
    lv_obj_set_width(ui_Min, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Min, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Min, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Min, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Min, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Hour = lv_img_create(ui_Clock_Panel);
    lv_img_set_src(ui_Hour, &ui_img_clock_hour_png);
    lv_obj_set_width(ui_Hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Hour, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Hour, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Hour, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Sec = lv_img_create(ui_Clock_Panel);
    lv_img_set_src(ui_Sec, &ui_img_clock_sec_png);
    lv_obj_set_width(ui_Sec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Sec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Sec, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Sec, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Sec, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Sec, 150);

    ui_Clock_Center = lv_obj_create(ui_Clock_Panel);
    lv_obj_set_width(ui_Clock_Center, 8);
    lv_obj_set_height(ui_Clock_Center, 8);
    lv_obj_set_align(ui_Clock_Center, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Clock_Center, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Clock_Center, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Clock_Center, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock_Center, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Clock_Center, lv_color_hex(0x1937D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Clock_Center, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Clock_Center, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date = ui_Small_Label_create(ui_Clock);
    lv_obj_set_x(ui_Date, 0);
    lv_obj_set_y(ui_Date, 76);
    lv_label_set_text(ui_Date, "Mon 28 Oct");
    lv_obj_set_style_text_color(ui_Date, lv_color_hex(0x9C9CD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scrolldots1 = ui_Scrolldots_create(ui_Clock);
    lv_obj_set_x(ui_Scrolldots1, 0);
    lv_obj_set_y(ui_Scrolldots1, -8);

    lv_obj_set_width(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D1), 4);
    lv_obj_set_height(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D1), 4);

    lv_obj_set_width(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), 8);
    lv_obj_set_height(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), 8);
    lv_obj_set_x(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), 11);
    lv_obj_set_y(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), 0);
    lv_obj_set_style_bg_color(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), lv_color_hex(0x101C52),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Clock, ui_event_Clock, LV_EVENT_ALL, NULL);

}
void ui_Usuario_screen_init(void)
{
    ui_Usuario = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Usuario, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Usuario, &ui_img_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Usuario, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scrolldots2 = ui_Scrolldots_create(ui_Usuario);
    lv_obj_set_x(ui_Scrolldots2, 0);
    lv_obj_set_y(ui_Scrolldots2, -8);

    lv_obj_set_width(ui_comp_get_child(ui_Scrolldots2, UI_COMP_SCROLLDOTS_D1), 4);
    lv_obj_set_height(ui_comp_get_child(ui_Scrolldots2, UI_COMP_SCROLLDOTS_D1), 4);

    lv_obj_set_x(ui_comp_get_child(ui_Scrolldots2, UI_COMP_SCROLLDOTS_D2), 10);
    lv_obj_set_y(ui_comp_get_child(ui_Scrolldots2, UI_COMP_SCROLLDOTS_D2), 0);

    lv_obj_set_width(ui_comp_get_child(ui_Scrolldots2, UI_COMP_SCROLLDOTS_D3), 8);
    lv_obj_set_height(ui_comp_get_child(ui_Scrolldots2, UI_COMP_SCROLLDOTS_D3), 8);
    lv_obj_set_x(ui_comp_get_child(ui_Scrolldots2, UI_COMP_SCROLLDOTS_D3), 21);
    lv_obj_set_y(ui_comp_get_child(ui_Scrolldots2, UI_COMP_SCROLLDOTS_D3), 0);
    lv_obj_set_style_bg_color(ui_comp_get_child(ui_Scrolldots2, UI_COMP_SCROLLDOTS_D3), lv_color_hex(0x101C52),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_Scrolldots2, UI_COMP_SCROLLDOTS_D3), 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Seleccion_usuario = lv_dropdown_create(ui_Usuario);
    lv_dropdown_set_options(ui_Seleccion_usuario, "Usuario1\nUsuario2\nUsuario3");
    lv_dropdown_set_text(ui_Seleccion_usuario, "Seleccione usuario");
    lv_obj_set_width(ui_Seleccion_usuario, 150);
    lv_obj_set_height(ui_Seleccion_usuario, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Seleccion_usuario, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Seleccion_usuario, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_muestra = lv_obj_create(ui_Seleccion_usuario);
    lv_obj_set_width(ui_muestra, 100);
    lv_obj_set_height(ui_muestra, 50);
    lv_obj_set_x(ui_muestra, 0);
    lv_obj_set_y(ui_muestra, 80);
    lv_obj_set_align(ui_muestra, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_muestra, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Usuario_seleccionado = lv_label_create(ui_Usuario);
    lv_obj_set_width(ui_Usuario_seleccionado, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Usuario_seleccionado, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Usuario_seleccionado, 0);
    lv_obj_set_y(ui_Usuario_seleccionado, 50);
    lv_obj_set_align(ui_Usuario_seleccionado, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Usuario_seleccionado, "Usuario seleccionado");

    lv_obj_add_event_cb(ui_Usuario, ui_event_Usuario, LV_EVENT_ALL, NULL);

}
void ui_Info_screen_init(void)
{
    ui_Info = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Info, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Info, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Info, &ui_img_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Info, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pary_Cloud = ui_Small_Label_create(ui_Info);
    lv_obj_set_x(ui_Pary_Cloud, 0);
    lv_obj_set_y(ui_Pary_Cloud, -67);
    lv_obj_set_align(ui_Pary_Cloud, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pary_Cloud, "Informacion general");
    lv_obj_set_style_text_color(ui_Pary_Cloud, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Pary_Cloud, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Indicadores = ui_Small_Label_create(ui_Info);
    lv_obj_set_x(ui_Indicadores, -17);
    lv_obj_set_y(ui_Indicadores, 36);
    lv_obj_set_align(ui_Indicadores, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Indicadores, "Tiempo restante\n\nTemperatura\n\nPotencia");
    lv_obj_set_style_text_color(ui_Indicadores, lv_color_hex(0x9C9CD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Indicadores, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scrolldots4 = ui_Scrolldots_create(ui_Info);
    lv_obj_set_x(ui_Scrolldots4, 0);
    lv_obj_set_y(ui_Scrolldots4, -8);

    lv_obj_set_width(ui_comp_get_child(ui_Scrolldots4, UI_COMP_SCROLLDOTS_D1), 4);
    lv_obj_set_height(ui_comp_get_child(ui_Scrolldots4, UI_COMP_SCROLLDOTS_D1), 4);

    lv_obj_set_x(ui_comp_get_child(ui_Scrolldots4, UI_COMP_SCROLLDOTS_D2), 10);
    lv_obj_set_y(ui_comp_get_child(ui_Scrolldots4, UI_COMP_SCROLLDOTS_D2), 0);

    lv_obj_set_x(ui_comp_get_child(ui_Scrolldots4, UI_COMP_SCROLLDOTS_D3), 20);
    lv_obj_set_y(ui_comp_get_child(ui_Scrolldots4, UI_COMP_SCROLLDOTS_D3), 0);

    lv_obj_set_x(ui_comp_get_child(ui_Scrolldots4, UI_COMP_SCROLLDOTS_D4), 30);
    lv_obj_set_y(ui_comp_get_child(ui_Scrolldots4, UI_COMP_SCROLLDOTS_D4), 0);

    lv_obj_set_width(ui_comp_get_child(ui_Scrolldots4, UI_COMP_SCROLLDOTS_D5), 8);
    lv_obj_set_height(ui_comp_get_child(ui_Scrolldots4, UI_COMP_SCROLLDOTS_D5), 8);
    lv_obj_set_x(ui_comp_get_child(ui_Scrolldots4, UI_COMP_SCROLLDOTS_D5), 41);
    lv_obj_set_y(ui_comp_get_child(ui_Scrolldots4, UI_COMP_SCROLLDOTS_D5), 0);
    lv_obj_set_style_bg_color(ui_comp_get_child(ui_Scrolldots4, UI_COMP_SCROLLDOTS_D5), lv_color_hex(0x101C52),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_Scrolldots4, UI_COMP_SCROLLDOTS_D5), 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Info, ui_event_Info, LV_EVENT_ALL, NULL);

}
void ui_Tiempo_carga_screen_init(void)
{
    ui_Tiempo_carga = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Tiempo_carga, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Tiempo_carga, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tiempo_carga, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Tiempo_carga, &ui_img_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Tiempo_carga, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm_container = lv_obj_create(ui_Tiempo_carga);
    lv_obj_set_width(ui_Alarm_container, lv_pct(100));
    lv_obj_set_height(ui_Alarm_container, lv_pct(100));
    lv_obj_set_align(ui_Alarm_container, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Alarm_container, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Alarm_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tiempo = ui_Small_Label_create(ui_Alarm_container);
    lv_obj_set_x(ui_Tiempo, 0);
    lv_obj_set_y(ui_Tiempo, 13);
    lv_obj_set_align(ui_Tiempo, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Tiempo, "Selecciona tiempo \n         de carga");
    lv_obj_set_style_text_color(ui_Tiempo, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Tiempo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_h2 = ui_Alarm_Comp_create(ui_Alarm_container);
    lv_obj_set_x(ui_h2, 0);
    lv_obj_set_y(ui_h2, 43);

    lv_label_set_text(ui_comp_get_child(ui_h2, UI_COMP_ALARM_COMP_ALARM_NUM2), "2:00");

    lv_label_set_text(ui_comp_get_child(ui_h2, UI_COMP_ALARM_COMP_PERIOD), "2 horas");

    ui_h5 = ui_Alarm_Comp_create(ui_Alarm_container);
    lv_obj_set_x(ui_h5, 0);
    lv_obj_set_y(ui_h5, 128);

    lv_label_set_text(ui_comp_get_child(ui_h5, UI_COMP_ALARM_COMP_ALARM_NUM2), "5:00");

    lv_label_set_text(ui_comp_get_child(ui_h5, UI_COMP_ALARM_COMP_PERIOD), "5 horas");

    lv_obj_add_state(ui_comp_get_child(ui_h5, UI_COMP_ALARM_COMP_SWITCH1), LV_STATE_CHECKED);       /// States

    ui_Carga_completa = ui_Alarm_Comp_create(ui_Alarm_container);
    lv_obj_set_x(ui_Carga_completa, 0);
    lv_obj_set_y(ui_Carga_completa, 213);

    lv_label_set_text(ui_comp_get_child(ui_Carga_completa, UI_COMP_ALARM_COMP_ALARM_NUM2), "10:00");

    lv_obj_set_x(ui_comp_get_child(ui_Carga_completa, UI_COMP_ALARM_COMP_PERIOD), 13);
    lv_obj_set_y(ui_comp_get_child(ui_Carga_completa, UI_COMP_ALARM_COMP_PERIOD), 3);
    lv_label_set_text(ui_comp_get_child(ui_Carga_completa, UI_COMP_ALARM_COMP_PERIOD), "Carga\ncompleta");

    ui_Scrolldots5 = ui_Scrolldots_create(ui_Tiempo_carga);
    lv_obj_set_x(ui_Scrolldots5, 0);
    lv_obj_set_y(ui_Scrolldots5, -8);

    lv_obj_set_width(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D1), 4);
    lv_obj_set_height(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D1), 4);

    lv_obj_set_x(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D2), 10);
    lv_obj_set_y(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D2), 0);

    lv_obj_set_x(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D3), 20);
    lv_obj_set_y(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D3), 0);

    lv_obj_set_x(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D4), 30);
    lv_obj_set_y(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D4), 0);

    lv_obj_set_x(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D5), 40);
    lv_obj_set_y(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D5), 0);

    lv_obj_set_width(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D6), 8);
    lv_obj_set_height(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D6), 8);
    lv_obj_set_x(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D6), 50);
    lv_obj_set_y(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D6), 0);
    lv_obj_set_style_bg_color(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D6), lv_color_hex(0x101C52),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_Scrolldots5, UI_COMP_SCROLLDOTS_D6), 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Tiempo_carga, ui_event_Tiempo_carga, LV_EVENT_ALL, NULL);

}

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_basic_init(dispp);
    lv_disp_set_theme(dispp, theme);
    ui_Inicio_screen_init();
    ui_Clock_screen_init();
    ui_Usuario_screen_init();
    ui_Info_screen_init();
    ui_Tiempo_carga_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Inicio);
}
